// Loads the Prometheus metric catalog generated by scripts/build-metrics.mjs
// from the fluxgate-proxy source. Fetched at runtime (the metrics page is a
// lazy route, so this never costs the initial bundle).

export interface MetricDef {
  name: string;
  type: string;
  help: string;
  labels: string[];
  group: string;
}

export interface MetricsCatalog {
  generatedAt: string;
  total: number;
  byGroup: Record<string, number>;
  byType: Record<string, number>;
  metrics: MetricDef[];
}

let cached: Promise<MetricsCatalog> | null = null;

export function getMetrics(): Promise<MetricsCatalog> {
  if (!cached) {
    cached = fetch('/metrics.json', { cache: 'force-cache' }).then((r) => {
      if (!r.ok) throw new Error(`metrics: HTTP ${r.status}`);
      return r.json() as Promise<MetricsCatalog>;
    });
  }
  return cached;
}
