// Generates public/metrics.json + src/generated/metricsSummary.ts from the
// fluxgate-proxy Prometheus metric DEFINITIONS in the Go source — so the
// Metrics reference can never drift from what the proxy actually exposes.
//
// Parses the source rather than scraping a running instance: most metrics are
// CounterVecs that don't appear on /metrics until first use, so a live scrape
// of an idle proxy is incomplete. The source has the full set with Help text
// and label keys. Runs LOCALLY; if the source files are missing it prints a
// warning and leaves the committed copy untouched (CI/Vercel stay green).
// Regenerate with:  npm run build:metrics
//
// Override source dir with FGP_SRC=/path/to/fluxgate-proxy

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = process.env.FGP_SRC || resolve(root, '../fluxgate-proxy');
const FILES = ['fgp/metrics.go', 'fgp/diameter_metrics.go'].map((f) => resolve(SRC, f));
const OUT = resolve(root, 'public/metrics.json');
const SUMMARY = resolve(root, 'src/generated/metricsSummary.ts');

function warnSkip(reason) {
  console.warn(`[build-metrics] ${reason} — keeping existing public/metrics.json + summary`);
  process.exit(0);
}

const present = FILES.filter(existsSync);
if (present.length === 0) warnSkip(`no metric source files found under ${SRC}`);

const TYPE_MAP = {
  CounterVec: 'counter', Counter: 'counter',
  GaugeVec: 'gauge', Gauge: 'gauge',
  HistogramVec: 'histogram', Histogram: 'histogram',
  SummaryVec: 'summary', Summary: 'summary',
};

// Each metric is a `factory.New<Type>(prometheus.<Type>Opts{ Namespace, [Subsystem,]
// Name, Help, ... }, []string{labels})` call. Split on those boundaries, then
// pull the fields out of each chunk. (The histogram `[]float64{...}` bucket
// slice is distinct from the `[]string{...}` label slice, so labels are
// unambiguous.)
const metrics = [];
const boundary = /\.New([A-Z]\w*)\(prometheus\.\w+Opts\{/g;

for (const file of present) {
  const text = readFileSync(file, 'utf8');
  const hits = [...text.matchAll(boundary)];
  for (let i = 0; i < hits.length; i++) {
    const start = hits[i].index;
    const end = i + 1 < hits.length ? hits[i + 1].index : text.length;
    const chunk = text.slice(start, end);
    const type = TYPE_MAP[hits[i][1]] || 'untyped';
    const name = chunk.match(/Name:\s*"([^"]+)"/)?.[1];
    if (!name) continue;
    const namespace = chunk.match(/Namespace:\s*"([^"]+)"/)?.[1] || '';
    const subsystem = chunk.match(/Subsystem:\s*"([^"]+)"/)?.[1] || '';
    const help = chunk.match(/Help:\s*"([^"]+)"/)?.[1] || '';
    const labelMatch = chunk.match(/\[\]string\{([^}]*)\}/);
    const labels = labelMatch
      ? [...labelMatch[1].matchAll(/"([^"]+)"/g)].map((m) => m[1])
      : [];
    const full = [namespace, subsystem, name].filter(Boolean).join('_');
    metrics.push({ name: full, type, help, labels, group: subsystem || 'proxy' });
  }
}

if (metrics.length === 0) warnSkip('parsed zero metrics from source');
metrics.sort((a, b) => a.name.localeCompare(b.name));

const byGroup = {};
const byType = {};
for (const m of metrics) {
  byGroup[m.group] = (byGroup[m.group] || 0) + 1;
  byType[m.type] = (byType[m.type] || 0) + 1;
}

const catalog = { generatedAt: new Date().toISOString().slice(0, 10), total: metrics.length, byGroup, byType, metrics };
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(catalog, null, 2) + '\n');

const summary = { generatedAt: catalog.generatedAt, total: catalog.total, byGroup, byType };
mkdirSync(dirname(SUMMARY), { recursive: true });
writeFileSync(
  SUMMARY,
  '// AUTO-GENERATED by scripts/build-metrics.mjs — do not edit by hand.\n' +
    '// Regenerate with `npm run build:metrics`.\n' +
    'export interface MetricsSummary {\n' +
    '  generatedAt: string;\n' +
    '  total: number;\n' +
    '  byGroup: Record<string, number>;\n' +
    '  byType: Record<string, number>;\n' +
    '}\n\n' +
    `export const metricsSummary: MetricsSummary = ${JSON.stringify(summary, null, 2)};\n`,
);

console.log(`[build-metrics] wrote ${metrics.length} metrics to public/metrics.json + src/generated/metricsSummary.ts`);
